# Generated by Django 5.2 on 2025-06-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        # Removed this operation since the full_name field doesn't exist
        # migrations.RemoveField(
        #     model_name='user',
        #     name='full_name',
        # ),
    ]
