# Generated by Django 5.1.11 on 2025-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='user',
            name='voss_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
