# Generated by Django 5.1.11 on 2025-06-14 13:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_transit', 'In Transit'), ('offline', 'Offline'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=20)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['agent_id'],
            },
        ),
        migrations.CreateModel(
            name='AgentDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('exception', 'Exception')], max_length=20)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('time_taken', models.DurationField()),
                ('confirmation_type', models.CharField(blank=True, choices=[('signature', 'Signature'), ('qr_scan', 'QR Scan')], max_length=20, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agent Deliveries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BaseOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
