# Generated by Django 5.1.11 on 2025-06-14 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='base_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='offices.office'),
        ),
    ]
