# Generated by Django 5.1.11 on 2025-06-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('offices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='base_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='offices.office'),
        ),
    ]
