# Generated by Django 5.2 on 2025-06-09 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('central_admin', 'Central Administration'), ('academic_faculty', 'Academic Faculty'), ('support_service', 'Support Service'), ('health_services', 'Health Services'), ('finance_division', 'Finance Division'), ('audit_unit', 'Audit Unit'), ('other', 'Other')], max_length=50)),
                ('unit_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('staff_count', models.IntegerField(default=0)),
                ('ongoing_transfers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['unit_type'], name='units_unit_unit_ty_f8d70b_idx'), models.Index(fields=['status'], name='units_unit_status_08f0cf_idx'), models.Index(fields=['unit_code'], name='units_unit_unit_co_4e567e_idx')],
            },
        ),
    ]
