# Generated by Django 5.1.11 on 2025-06-14 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('central_admin', 'Central Administration'), ('academic_faculty', 'Academic Faculty'), ('support_service', 'Support Service'), ('health_services', 'Health Services'), ('finance_division', 'Finance Division'), ('audit_unit', 'Audit Unit'), ('library', 'Library'), ('student_affairs', 'Student Affairs'), ('human_resources', 'Human Resources'), ('it_services', 'IT Services'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('unit_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('staff_count', models.IntegerField(default=0)),
                ('ongoing_transfers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
