# Generated by Django 5.1.11 on 2025-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('central_admin', 'Central Administration'), ('academic_faculty', 'Academic Faculty'), ('support_service', 'Support Service'), ('health_services', 'Health Services'), ('finance_division', 'Finance Division'), ('audit_unit', 'Audit Unit'), ('library', 'Library'), ('student_affairs', 'Student Affairs'), ('human_resources', 'Human Resources'), ('it_services', 'IT Services'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50),
        ),
    ]
