# Generated by Django 5.2 on 2025-06-09 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('self', 'Self Delivery'), ('agent', 'Agent Delivery')], max_length=10)),
                ('agent_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('immediate', 'Immediate')], default='normal', max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('notifications', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('recalled', 'Recalled'), ('escalated', 'Escalated'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('revision_requested', 'Revision Requested'), ('force_returned', 'Force Returned')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('history', models.JSONField(default=list)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='offices.office')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='folders.folder')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='offices.office')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_steps', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_steps', to=settings.AUTH_USER_MODEL)),
                ('unit_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_steps', to='offices.office')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='transfers.transfer')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('transfer', 'step_number')},
            },
        ),
    ]
