# Generated by Django 5.1.11 on 2025-06-14 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('self', 'Self Delivery'), ('agent', 'Agent Delivery')], max_length=10)),
                ('agent_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('immediate', 'Immediate')], default='normal', max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('notifications', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('recalled', 'Recalled'), ('escalated', 'Escalated'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('revision_requested', 'Revision Requested'), ('force_returned', 'Force Returned')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('history', models.JSONField(default=list)),
                ('collected_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
