# Generated by Django 5.1.11 on 2025-06-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0002_initial'),
        ('offices', '0002_initial'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routingstep',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routingstep',
            name='responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routingstep',
            name='unit_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_steps', to='offices.office'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_incoming', to='offices.office'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_outgoing', to='offices.office'),
        ),
        migrations.AddField(
            model_name='routingstep',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='transfers.transfer'),
        ),
        migrations.AlterUniqueTogether(
            name='routingstep',
            unique_together={('transfer', 'step_number')},
        ),
    ]
