# Generated by Django 5.1.11 on 2025-06-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_initial'),
        ('transfers', '0002_transfer_collected_at_transfer_collected_by'),
    ]

    operations = [
    ]
