# Generated by Django 5.1.11 on 2025-06-15 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('comment_type', models.CharField(choices=[('general', 'General Comment'), ('escalation', 'Escalation Note'), ('return', 'Return Note'), ('rejection', 'Rejection Note'), ('revision', 'Revision Request'), ('agent', 'Agent Note')], default='general', max_length=20)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='transfers.transfercomment')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='transfers.transfer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
