# Generated by Django 5.1.11 on 2025-06-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_delete_externaloffice_delete_internaloffice_and_more'),
        ('transfers', '0003_merge_20250611_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='collected_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='destination_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='offices.office'),
        ),
    ]
