# Generated by Django 5.1.11 on 2025-06-13 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transfer_collected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
