# Generated by Django 5.1.11 on 2025-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_alter_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
