# Generated by Django 5.1.11 on 2025-06-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_add_archived_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at'], 'permissions': [('can_confirm_delivery', 'Can confirm transfer delivery')]},
        ),
    ]
