# Generated by Django 5.1.11 on 2025-06-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_alter_transfer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_pickup', 'Pending Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('recalled', 'Recalled'), ('escalated', 'Escalated'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('revision_requested', 'Revision Requested'), ('force_returned', 'Force Returned'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
