# Generated by Django 5.1.11 on 2025-06-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_alter_transfer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at'], 'permissions': [('can_confirm_delivery', 'Can confirm delivery of transfers'), ('can_confirm_pickup', 'Can confirm pickup of transfers'), ('can_manage_transfers', 'Can manage all transfers'), ('can_escalate_transfers', 'Can escalate transfers'), ('can_return_transfers', 'Can return transfers'), ('can_handle_returns', 'Can handle returned transfers')]},
        ),
    ]
