# Generated by Django 5.1.11 on 2025-06-17 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_initial'),
        ('transfers', '0008_alter_transfer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at'], 'permissions': [('can_confirm_delivery', 'Can confirm transfer delivery')]},
        ),
        migrations.AlterField(
            model_name='transfer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transfers', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('recalled', 'Recalled'), ('escalated', 'Escalated'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('revision_requested', 'Revision Requested'), ('force_returned', 'Force Returned'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
