# Generated by Django 5.1.11 on 2025-06-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('folders', '0001_initial'),
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='current_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_folders', to='offices.office'),
        ),
        migrations.AddField(
            model_name='folder',
            name='destination_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_folders', to='offices.office'),
        ),
        migrations.AddField(
            model_name='folder',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='source_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_folders', to='offices.office'),
        ),
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='folders.foldercategory'),
        ),
        migrations.AddField(
            model_name='foldercomment',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='foldercomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='folders.foldercomment'),
        ),
        migrations.AddField(
            model_name='foldercomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderfile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_folder_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderfile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_folder_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='folderfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='folders.folderservice'),
        ),
        migrations.AddField(
            model_name='foldersignature',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='foldersignature',
            name='signed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foldersignature',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foldertransfer',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_transfers', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='foldertransfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folder_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foldertransfer',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_transfers', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='foldertransfer',
            name='from_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_outgoing_transfers', to='offices.office'),
        ),
        migrations.AddField(
            model_name='foldertransfer',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foldertransfer',
            name='to_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_incoming_transfers', to='offices.office'),
        ),
        migrations.AddField(
            model_name='folderworkflowstep',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workflow_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderworkflowstep',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='folderworkflowstep',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='offices.office'),
        ),
        migrations.AddField(
            model_name='folderworkflowstep',
            name='responsible_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_workflow_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='retention_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='folders.retentionclass'),
        ),
        migrations.AddIndex(
            model_name='folderfile',
            index=models.Index(fields=['folder', 'uploaded_at'], name='folders_fol_folder__310fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='folderfile',
            index=models.Index(fields=['file_type'], name='folders_fol_file_ty_0723dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderworkflowstep',
            unique_together={('folder', 'step_number')},
        ),
    ]
