# Generated by Django 5.2 on 2025-06-10 06:52

import django.db.models.deletion
import folders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_collected_at_folder_collected_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderfile',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='folderfile',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='folderfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folderfile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_folder_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_folder_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='file',
            field=models.FileField(upload_to=folders.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='file_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folderfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='folderfile',
            index=models.Index(fields=['folder', 'uploaded_at'], name='folders_fol_folder__310fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='folderfile',
            index=models.Index(fields=['file_type'], name='folders_fol_file_ty_0723dd_idx'),
        ),
    ]
