# Generated by Django 5.1.11 on 2025-06-14 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users who want to receive notifications about this folder', related_name='watched_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
