# Generated by Django 5.1.11 on 2025-06-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_initial'),
        ('folders', '0003_remove_folderfile_file_number_and_more'),
    ]

    operations = [
    ]
