# Generated by Django 5.1.11 on 2025-06-11 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_merge_20250611_1550'),
        ('offices', '0004_delete_externaloffice_delete_internaloffice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='current_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_folders', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='destination_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_folders', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='source_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_folders', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='foldercategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='folderservice',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
