# Generated by Django 5.1.11 on 2025-06-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_alter_folder_current_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='folders.foldercategory'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='retention_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='folders.retentionclass'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='folders.folderservice'),
        ),
    ]
