# Generated by Django 5.1.11 on 2025-06-12 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_alter_folder_category_alter_folder_retention_class_and_more'),
        ('units', '0003_alter_unit_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folderservice',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folderservice',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderservice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('normal', 'Normal'), ('URGENT', 'Urgent'), ('confidential', 'Confidential')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='folder',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='units.unit', verbose_name='Unit of Origin'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('Not Started', 'Not Started'), ('In Transit', 'In Transit'), ('DELIVERED', 'Delivered'), ('Overdue', 'Overdue'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='folder',
            name='subject',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foldertransfer',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('normal', 'Normal'), ('URGENT', 'Urgent'), ('confidential', 'Confidential')], default='normal', max_length=20),
        ),
    ]
