# Generated by Django 5.1.11 on 2025-06-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0007_folderservice_archived_at_folderservice_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.folder'),
        ),
    ]
