# Generated by Django 5.1.11 on 2025-06-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0008_alter_folderfile_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderfile',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
