# Generated by Django 5.1.11 on 2025-06-13 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0009_folderfile_is_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
