# Generated by Django 5.1.11 on 2025-06-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0010_alter_folderfile_id'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE folders_folderfile ADD COLUMN is_temporary BOOLEAN DEFAULT FALSE",
            "ALTER TABLE folders_folderfile DROP COLUMN is_temporary"
        ),
    ]
