# Generated by Django 5.1.11 on 2025-06-14 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=255)),
                ('office_type', models.CharField(choices=[('Faculty-Level', 'Faculty-Level'), ('Departmental', 'Departmental'), ('Support Office', 'Support Office'), ('Record Storage', 'Record Storage')], max_length=50)),
                ('office_code', models.CharField(max_length=50, unique=True)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['office_name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Overdue', 'Overdue')], max_length=20)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OfficeTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('party', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Delivered', 'Delivered'), ('In Transit', 'In Transit'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
