# Generated by Django 5.1.11 on 2025-06-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaloffice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='internaloffice',
            name='head_of_office',
        ),
        migrations.RemoveField(
            model_name='internaloffice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='officestaffmember',
            name='office',
        ),
        migrations.AlterUniqueTogether(
            name='officestaffmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='officestaffmember',
            name='user',
        ),
    ]
