# Generated by Django 5.1.11 on 2025-06-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_initial'),
        ('units', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='units.unit'),
        ),
    ]
