# Generated by Django 5.1.11 on 2025-06-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_remove_externaloffice_updated_by_and_more'),
        ('search', '0003_alter_searchfilters_destination_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalOffice',
        ),
        migrations.DeleteModel(
            name='InternalOffice',
        ),
        migrations.DeleteModel(
            name='OfficeStaffMember',
        ),
    ]
