# Generated by Django 5.2 on 2025-06-09 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('folders', '0001_initial'),
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='agents.agent')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_activities', to='folders.foldertransfer')),
            ],
            options={
                'verbose_name_plural': 'Agent Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchFilters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_term', models.CharField(max_length=255)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('active', 'Active'), ('archived', 'Archived'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('in_review', 'In Review'), ('awaiting_pickup', 'Awaiting Pickup')], max_length=20, null=True)),
                ('treatment_folder_id', models.CharField(blank=True, max_length=50, null=True)),
                ('specific_file_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_filters', to='agents.agent')),
                ('destination_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_filters', to='offices.externaloffice')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_filters', to='offices.internaloffice')),
            ],
            options={
                'verbose_name_plural': 'Search Filters',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_term', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(max_length=50)),
                ('result_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.searchhistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('in_review', 'In Review'), ('awaiting_pickup', 'Awaiting Pickup')], max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_results', to='offices.internaloffice')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='folders.folderfile')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='folders.folder')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='TransferPathStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('sent', 'Sent')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_path_steps', to='folders.folder')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_path_steps', to='offices.internaloffice')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransferTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_position', models.JSONField(help_text="Current position information: {'office': str, 'status': str}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_trail', to='folders.folder')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
