# Generated by Django 5.1.11 on 2025-06-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0002_initial'),
        ('offices', '0002_initial'),
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='search_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.searchhistory'),
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='current_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_results', to='offices.office'),
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='folders.folderfile'),
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='transferpathstep',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_path_steps', to='folders.folder'),
        ),
        migrations.AddField(
            model_name='transferpathstep',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_path_steps', to='offices.office'),
        ),
        migrations.AddField(
            model_name='transfertrail',
            name='folder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_trail', to='folders.folder'),
        ),
    ]
