# Generated by Django 5.1.11 on 2025-06-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_remove_externaloffice_updated_by_and_more'),
        ('search', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfilters',
            name='destination_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_search_filters', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='searchfilters',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_search_filters', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='current_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_results', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='transferpathstep',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_path_steps', to='offices.office'),
        ),
    ]
