# Generated by Django 5.1.11 on 2025-06-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationhistoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='personalnotificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel'),
        ),
        migrations.AddField(
            model_name='usernotificationchannel',
            name='user_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.personalnotificationsettings'),
        ),
        migrations.AddField(
            model_name='personalnotificationsettings',
            name='channels',
            field=models.ManyToManyField(through='notifications.UserNotificationChannel', to='notifications.notificationchannel'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationpreference'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='user_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.personalnotificationsettings'),
        ),
        migrations.AddField(
            model_name='personalnotificationsettings',
            name='preferences',
            field=models.ManyToManyField(through='notifications.UserNotificationPreference', to='notifications.notificationpreference'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationchannel',
            unique_together={('user_settings', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationpreference',
            unique_together={('user_settings', 'preference')},
        ),
    ]
